{% set name = "pyswagger" %}
{% set version = "0.8.39" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bde5b9aeebf0b032556aecd898e47264e84eefecd6249a0dc0dd826fd0640dd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pyaml >=15.03.1
    - python >={{ python_min }}
    - six >=1.7.2
    - validate_email

test:
  imports:
    - pyswagger
    - pyswagger.consts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyswagger/
  summary: A type-safe, dynamic, spec-compliant swagger client & converter for python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
